# ---------------- #
#   Main Configs   #
# ---------------- #
title: Jevic
author: Jevic
subtitle: "前路漫漫,忆往昔......"
description: "前路漫漫,忆往昔......"
keywords: Jevic
url: "http://www.jevic.cn"
date_format: "ordinal"
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/jevic/jevic.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
organization: Jevic, Inc.
organization_url: http://www.jevic.cn
location: Shenzhen, China
email: jevic@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基
  

  -
    href: /open-source/
    label: 开源

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
    - jekyll-sitemap
#    - jekyll-seo-tag
#    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-feed
    - jemoji
#    - jekyll-mentions
    - jekyll-github-metadata
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: jevic
#douban_username: jevic
facebook_username: jevic
#weibo_username: jevic
#zhihu_username: jevic
twitter_username: jevic

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
disqus_username: jevic-cn
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: jevic
#    repo: blog-comments
#    oauth:
#        client_id: d2e1cbbd298958076462
#        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
## https://github.com/gitalk/gitalk#install
#gitalk:
#    owner: jevic
#    repo: blog-comments
#    clientID: d2e1cbbd298958076462
#    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-82387173-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Python, shell, Docker,Linux]
skill_mobile_app_keywords: [Python]
#skill_windows_keywords: []

# ---------------- #
# Github metadata  #
# ---------------- #
repository: jevic/jevic.github.io
